### ISSUE TITLE
KeyError: 'inception_4b/pool_proj-nozoom'

### ISSUE THREAD

**Issue by wrenchpilot** [deepdream-community/openDream#1]
blobs.py includes a few blob keys that I can't find.  I was running through all the keys when it crashed at the 'inception_4b/pool_proj-nozoom' key.  Where can I find these?

**Comment by SlimeQ** [comment]
as far as I can tell, those blobs just cannot output and so they error out. I've actually stopped using blobs.py and directly referencing net.blobs instead but those blobs are still skipped. I'll push it to master later tonight but in the meantime you can just replace blobs.get() with net.blobs.keys()

**Comment by SlimeQ** [comment]
It's also concerning that that error is not being caught. are you on the latest commit? I made a ton of awful commits yesterday because I was working off two computers simultaneously and shit got crossed.

**Comment by wrenchpilot** [comment]
Thanks for the fast response.  It's probably because I forked and pulled from my repo. Re-cloning from your repo and testing now.

**Comment by SlimeQ** [comment]
i'm also seeing that i merged poorly and there's now two loops under blobs=all...
be sure to sanity check this. my current fork is running like a... well, a dream. also has a few optimizations in deepdream.py that cut several seconds (!!!) off the execution time of large batches (lololol).

i'll make sure to push it when i get home around 7

**Comment by wrenchpilot** [comment]
Right on, thanks!

**Comment by SlimeQ** [comment]
also, if you come up with a stabler version, feel free to commit. in theory i'd like this to be more of a collaborative effort. i haven't quite figured out how workflow, branch structure, stable releases, etc should be yet. i think we probably need a develop branch to push new stuff to, then we can merge that with master when we know it's stable. we both have our own forks, so these should probably be merged eventually.

btw i've invited you as owner

**Comment by SlimeQ** [comment]
hey, i just pushed the version i've been running all day. if you find the time, go ahead and merge your stuff into the dev-1.0 branch. i looked at the tree and saw that we're probably going to have a few conflicts. i'll create issues for the one's i know of, but if you notice something i missed you should add it. once they're all in their own threads then we can discuss and figure out the best course of action.

as far as i'm concerned, workflow was the real issue here. case closed.
