### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by SlimeQ** [deepdream-community/openDream#3]
i want to have a web interface that can be used to send/receive images to the program, and also have a webcam. the logistics here can go a few ways. probably the most sensible way is to have a python web server which simply receives images and processes them. however, python is going to be quite busy between requests, so i think it makes the most sense to have it block at this time and then re-open the connection on completion and send the processed file back. of course this will make it impossible to remotely stop the process, which is unfortunate. i've been tossing around the idea of having a node.js server which is capable of handling requests asynchronously and starting/killing the process on command. it would also accept images from the python process via a socket as it ran, which it could then dump to database, email to tumblr, or push to a connected user. i think this is a good idea.

suggestions are welcome. i've noticed that clouddream has an interface already that has much of this functionality, so that is definitely worth looking into.

**Comment by SlimeQ** [comment]
[this is a working implementation of a webcam server for deepdream](https://github.com/deepdream-community/luciddream)

luciddream.py opens a webserver on a specified port and listens for POST requests containing base64 encoded images. it is not terribly efficient but i'm able to get 2-3 second lag on my very low end pc/graphics card with the right settings. As of now I have a node.js instance handling all file i/o and communicating with the client, and it spawns luciddream.py and communicates with it by making requests to localhost on a given port. this is not ideal for this application (it should be sockets all the way down) but in general this is a step in the right direction. android app on the way.

i'm not totally sure how to go about adding luciddream to this project, however. it should probably be in it's own folder because it has a lot of dependencies and needs a readme, but then it needs to be able to link in to the deepdream.py in a different folder. i didn't quite get this working yet, so i'm leaving the issue open until luciddream gets properly merged into the opendream repository.

**Comment by OverStruck** [comment]
This is an interesting project. I'll take it a look at it in the following days :)

**Comment by SlimeQ** [comment]
I am closing this issue because it's more or less been done. [I've created a new issue with regards to packaging here.](https://github.com/deepdream-community/opendream/issues/4)
